[jwt]
secret = "49y5qOJ5/WA8Jpn5eqlNUA/iWNbdVg6pJhxYZsD4Wwb/qTnWr+Z9CM6FzxwupQDyjQF8/Ee09l//kPcywRtyPw=="
issuer = "Randware.org"
audience = "Quota"
expiryMinutes = 5000

[oauth]
id = "1331219516549501019"
secret = "FFMDTE6CWb92mwQ3ivb-cfJCCzHqQPJU"
apiEndpoint = "https://discord.com/api/v10"

[openapi]
enabled = true

[server]
port = 5000

[bot]
token = "MTMzMTIxOTUxNjU0OTUwMTAxOQ.G1T4oL.1QqPQefvv-ygf7skpAZutT-9lX8HqmjosgEMqA"
